substitutions:
  IN_RJ45_1: "7"
  IN_RJ45_2: "6"
  IN_RJ45_3: "5"
  IN_RJ45_4: "4"
  IN_RJ45_5: "3"
  IN_RJ45_6: "2"
  IN_RJ45_7: "1"
  IN_RJ45_8: "0"

  IN_RJ45_9: "8"
  IN_RJ45_10: "9"
  IN_RJ45_11: "10"
  IN_RJ45_12: "11"
  IN_RJ45_13: "12"
  IN_RJ45_14: "13"
  IN_RJ45_15: "14"
  IN_RJ45_16: "15"

  IN_RJ45_17: "7"
  IN_RJ45_18: "6"
  IN_RJ45_19: "5"
  IN_RJ45_20: "4"
  IN_RJ45_21: "3"
  IN_RJ45_22: "2"
  IN_RJ45_23: "1"
  IN_RJ45_24: "0"

  IN_RJ45_25: "8"
  IN_RJ45_26: "9"
  IN_RJ45_27: "10"
  IN_RJ45_28: "11"
  IN_RJ45_29: "12"
  IN_RJ45_30: "13"
  IN_RJ45_31: "14"
  IN_RJ45_32: "15"

  OUT_RJ45_1: "7"
  OUT_RJ45_2: "6"
  OUT_RJ45_3: "5"
  OUT_RJ45_4: "4"
  OUT_RJ45_5: "3"
  OUT_RJ45_6: "2"
  OUT_RJ45_7: "1"
  OUT_RJ45_8: "0"

  OUT_RJ45_9: "8"
  OUT_RJ45_10: "9"
  OUT_RJ45_11: "10"
  OUT_RJ45_12: "11"
  OUT_RJ45_13: "12"
  OUT_RJ45_14: "13"
  OUT_RJ45_15: "14"
  OUT_RJ45_16: "15"

  OUT_RJ45_17: "7"
  OUT_RJ45_18: "6"
  OUT_RJ45_19: "5"
  OUT_RJ45_20: "4"
  OUT_RJ45_21: "3"
  OUT_RJ45_22: "2"
  OUT_RJ45_23: "1"
  OUT_RJ45_24: "0"

  OUT_RJ45_25: "8"
  OUT_RJ45_26: "9"
  OUT_RJ45_27: "10"
  OUT_RJ45_28: "11"
  OUT_RJ45_29: "12"
  OUT_RJ45_30: "13"
  OUT_RJ45_31: "14"
  OUT_RJ45_32: "15"

  rooms_name: "salon taras, salon FIX, salon od sąsiada, jadalnia, kuchnia wyjście na taras, kuchnia okno, gabinet parter okno lewe, gabinet parter okno prawe, garaż, pokój od sąsiada, kacperek okno lewe, kacperek okno prawe, sypialnia prawa, sypialnia lewa, garderoba sypialnia, korytarz"
  rooms_id:   "salon_taras, salon_fix, salon_od_sasiada, jadalnia, kuchnia_wyjscie_na_taras, kuchnia_okno, gabinet_parter_okno_lewe, gabinet_parter_okno_prawe, garaz, pokoj_od_sasiada, kacperek_okno_lewe, kacperek_okno_prawe, sypialnia_prawa, sypialnia_lewa, garderoba_sypialnia, korytarz"
  blind_count: "8"

  # serial_prefix: esp #Don't change it.

esphome:
  name: krishomelight
  friendly_name: KrisHomeLight
  libraries:
    - EEPROM
  # on_boot:
  #   priority: -100
  #   then:
  #     - delay: 5s
  #     - lambda: |-
  #         float stored_position = id(eeprom_storage).read_position(0);
  #         id(cover1).position = stored_position;

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BEqOF0qtQfbC6LIhC9nV/pkj7dXO4x3FLfaEZNDS6WY="

ota:
  - platform: esphome
    password: "e2789d68b00c626967b9b7a784bce4a2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Krishomelight Fallback Hotspot"
    password: "Lf8ri3xZq7OX"

captive_portal:

# ******************
# Moja konfiguracja
# ******************

# Konfiguracja I2C
i2c:
  sda: GPIO4  # D2 na płytce
  scl: GPIO5  # D1 na płytce
  frequency: 400kHz
  scan: true

# Załadowanie biblioteki dla EEPROM AT24C256
# external_components:
#   - source: my_components
  
# at24c256_eeprom:
#   id: eeprom_storage

# Definicja czcionek
font:
  - file: 'arial.ttf'
    id: font_small
    size: 10
  - file: 'arial.ttf'
    id: font_large
    size: 16

# MCP23017
mcp23017:
  - id: 'mcp23017_in_1_16'
    address: 0x20
  - id: 'mcp23017_out_1_16'
    address: 0x21

# Obsługa wyświetlacza
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    reset_pin: GPIO2
    address: 0x3C
    update_interval: 1000ms # Aktualizacja co sekundę
    lambda: |-
      it.printf(0, 0, id(font_small), "IP: %s", id(ip_address).state.c_str());
      //it.printf(0, 10, id(font_small), "WiFi: %d dBm (%.0f%%)", 
      //          (int)id(wifi_signal_db).state, 
      //          id(wifi_signal_percent).state);
      //int switches_on = 0;
      //for (auto *sw : App.get_switches()) {
      //  if (sw->state) {
      //    switches_on++;
      //  }
      //}
      //it.printf(0, 20, id(font_small), "Pozycja rolety: %.1f%%", id(cover1).position * 100);
      //it.printf(0, 20, id(font_small), "L: %d ON, S: %d ON", lights_on, switches_on);
      

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: ip_address

switch:
  - platform: gpio
    name: Roleta salon taras UP
    pin:
      mcp23xxx: mcp23017_out_1_16
      number: ${OUT_RJ45_1}
      mode: OUTPUT
    id: relay_salon_taras_up
    inverted: true
    internal: false
    interlock:
    - relay_salon_taras_down
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: Roleta salon taras DOWN
    pin:
      mcp23xxx: mcp23017_out_1_16
      number: ${OUT_RJ45_2}
      mode: OUTPUT
    id: relay_salon_taras_down
    inverted: true
    internal: false
    interlock:
    - relay_salon_taras_up
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: Roleta salon FIX UP
    pin:
      mcp23xxx: mcp23017_out_1_16
      number: ${OUT_RJ45_3}
      mode: OUTPUT
    id: relay_salon_FIX_up
    inverted: true
    internal: false
    interlock:
    - relay_salon_FIX_down
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: Roleta salon FIX DOWN
    pin:
      mcp23xxx: mcp23017_out_1_16
      number: ${OUT_RJ45_4}
      mode: OUTPUT
    id: relay_salon_FIX_down
    inverted: true
    internal: false
    interlock:
    - relay_salon_FIX_up
    restore_mode: ALWAYS_OFF